# Generated by Django 4.2.7 on 2025-10-20 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('size', models.CharField(choices=[('4x4', "4' x 4' (16 sq ft)"), ('4x8', "4' x 8' (32 sq ft)"), ('8x8', "8' x 8' (64 sq ft)"), ('10x10', "10' x 10' (100 sq ft)"), ('custom', 'Custom Size')], default='10x10', max_length=20)),
                ('width', models.IntegerField(default=10, help_text='Width in feet')),
                ('height', models.IntegerField(default=10, help_text='Height in feet')),
                ('layout_data', models.JSONField(default=dict, help_text='Grid layout as JSON')),
                ('is_public', models.BooleanField(default=False, help_text='Allow others to view this garden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latin_name', models.CharField(max_length=150)),
                ('symbol', models.CharField(help_text='1-2 character symbol for grid', max_length=2)),
                ('color', models.CharField(default='#90EE90', help_text='Hex color code', max_length=7)),
                ('plant_type', models.CharField(choices=[('vegetable', 'Vegetable'), ('herb', 'Herb'), ('flower', 'Flower'), ('fruit', 'Fruit'), ('companion', 'Companion Plant'), ('cover_crop', 'Cover Crop')], max_length=20)),
                ('planting_season', models.CharField(choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('year_round', 'Year Round')], max_length=20)),
                ('days_to_harvest', models.IntegerField(blank=True, null=True)),
                ('spacing_inches', models.FloatField(help_text='Spacing between plants in inches')),
                ('chicago_notes', models.TextField(blank=True, help_text='Chicago Zone 5b/6a specific notes')),
                ('pest_deterrent_for', models.TextField(blank=True, help_text='Comma-separated list of pests deterred')),
                ('is_default', models.BooleanField(default=False, help_text='Default system plant')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('companion_plants', models.ManyToManyField(blank=True, to='gardens.plant')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'created_by')},
            },
        ),
        migrations.CreateModel(
            name='PlantingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('note_text', models.TextField(help_text='Your observations, tasks, or reminders')),
                ('grid_position', models.CharField(blank=True, help_text='Position in grid (e.g., "A3" or "2,5")', max_length=10)),
                ('note_date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='gardens.garden')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gardens.plant')),
            ],
            options={
                'ordering': ['-note_date', '-created_at'],
            },
        ),
    ]
