# Generated by Django 5.2.4 on 2025-10-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='planting_season',
        ),
        migrations.AddField(
            model_name='plant',
            name='planting_seasons',
            field=models.JSONField(default=list, help_text='List of seasons when this plant can be planted (e.g., ["spring", "fall"])'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='plant_type',
            field=models.CharField(choices=[('utility', 'Utility'), ('vegetable', 'Vegetable'), ('herb', 'Herb'), ('flower', 'Flower'), ('fruit', 'Fruit'), ('companion', 'Companion Plant'), ('cover_crop', 'Cover Crop')], max_length=20),
        ),
    ]
