# Generated by Django 5.2.4 on 2025-10-22 07:23

from django.db import migrations


def update_planting_seasons(apps, schema_editor):
    """Update existing plants with multiple planting seasons"""
    Plant = apps.get_model('gardens', 'Plant')

    # Define plants that can be planted in multiple seasons
    multi_season_plants = {
        'Kale': ['spring', 'fall'],
        'Carrots': ['spring', 'summer', 'fall'],
        'Lettuce': ['spring', 'summer', 'fall'],
        'Radishes': ['spring', 'fall'],
        'Spinach': ['spring', 'fall'],
    }

    # Update plants with multiple seasons
    for plant_name, seasons in multi_season_plants.items():
        Plant.objects.filter(name=plant_name, is_default=True).update(planting_seasons=seasons)

    print(f"Updated {len(multi_season_plants)} plants with multiple planting seasons")


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0002_remove_plant_planting_season_plant_planting_seasons_and_more'),
    ]

    operations = [
        migrations.RunPython(update_planting_seasons, migrations.RunPython.noop),
    ]
