# Generated by Django 5.2.4 on 2025-10-22 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0003_update_planting_seasons_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='life_cycle',
            field=models.CharField(blank=True, choices=[('annual', 'Annual'), ('biennial', 'Biennial'), ('perennial', 'Perennial')], help_text='Annual, Biennial, or Perennial', max_length=10),
        ),
    ]
