# Generated by Django 5.2.4 on 2025-10-22 08:00

from django.db import migrations


def update_life_cycles(apps, schema_editor):
    """Update existing plants with life cycle information"""
    Plant = apps.get_model('gardens', 'Plant')

    # Define life cycles for each default plant
    life_cycles = {
        'Strawberries': 'perennial',
        'Tomatoes': 'annual',
        'Kale': 'biennial',
        'Carrots': 'biennial',
        'Brussels Sprouts': 'biennial',
        'Yukon Gold Potatoes': 'annual',
        'Lettuce': 'annual',
        'Garlic': 'perennial',
        'Basil': 'annual',
        'Radishes': 'annual',
        'Marigolds': 'annual',
        'Sage': 'perennial',
        'Spinach': 'annual',
        'Chives': 'perennial',
        'Nasturtiums': 'annual',
        'Dill': 'annual',
        'Horseradish': 'perennial',
        'Thyme': 'perennial',
        'Path': 'annual',
        'Empty Space': 'annual',
    }

    # Update each plant
    for plant_name, life_cycle in life_cycles.items():
        Plant.objects.filter(name=plant_name, is_default=True).update(life_cycle=life_cycle)

    print(f"Updated {len(life_cycles)} plants with life cycle information")


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0004_plant_life_cycle'),
    ]

    operations = [
        migrations.RunPython(update_life_cycles, migrations.RunPython.noop),
    ]
