# Generated by Django 4.2.7 on 2025-10-23 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0005_update_plant_life_cycles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.IntegerField(help_text='Row position in garden grid (0-indexed)')),
                ('col', models.IntegerField(help_text='Column position in garden grid (0-indexed)')),
                ('planted_date', models.DateField(blank=True, help_text='Date when this plant was planted', null=True)),
                ('expected_harvest_date', models.DateField(blank=True, help_text='Expected harvest date (auto-calculated from planted_date + days_to_harvest)', null=True)),
                ('actual_harvest_date', models.DateField(blank=True, help_text='Actual date when harvested', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_instances', to='gardens.garden')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='gardens.plant')),
            ],
            options={
                'ordering': ['garden', 'row', 'col'],
                'indexes': [models.Index(fields=['garden', 'row', 'col'], name='gardens_pla_garden__5cdaa2_idx'), models.Index(fields=['planted_date'], name='gardens_pla_planted_5ec9c2_idx'), models.Index(fields=['expected_harvest_date'], name='gardens_pla_expecte_463411_idx')],
                'unique_together': {('garden', 'row', 'col')},
            },
        ),
    ]
