# Generated by Django 4.2.7 on 2025-10-24 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0006_plantinstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='yield_per_plant',
            field=models.CharField(blank=True, help_text='Expected yield per plant (e.g., "2-3 lbs", "10-15 fruits", "continuous harvest")', max_length=100),
        ),
    ]
