# Generated by Django 4.2.7 on 2025-10-24 01:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0007_plant_yield_per_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='GardenShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(help_text='Email of person to share with', max_length=254)),
                ('permission', models.CharField(choices=[('view', 'Can View'), ('edit', 'Can Edit')], default='view', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('garden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='gardens.garden')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_created', to=settings.AUTH_USER_MODEL)),
                ('shared_with_user', models.ForeignKey(blank=True, help_text='User object once they register/login', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shared_gardens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('garden', 'shared_with_email')},
            },
        ),
    ]
