# Generated by Django 4.2.7 on 2025-11-15 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0008_gardenshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='days_to_germination',
            field=models.IntegerField(blank=True, help_text='Days for seeds to germinate', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='direct_sow',
            field=models.BooleanField(default=False, help_text='Can this plant be directly sown outdoors?'),
        ),
        migrations.AddField(
            model_name='plant',
            name='transplant_to_harvest_days',
            field=models.IntegerField(blank=True, help_text='Days from transplanting to harvest (if different from days_to_harvest)', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='weeks_after_last_frost_transplant',
            field=models.IntegerField(blank=True, help_text='Weeks after last frost to transplant outdoors (0 = at last frost, negative = before)', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='weeks_before_last_frost_start',
            field=models.IntegerField(blank=True, help_text='Weeks before last frost to start seeds indoors (e.g., 6-8 for tomatoes)', null=True),
        ),
        migrations.AddField(
            model_name='plantinstance',
            name='seed_started_date',
            field=models.DateField(blank=True, help_text='Date when seeds were started indoors', null=True),
        ),
        migrations.AddField(
            model_name='plantinstance',
            name='transplanted_date',
            field=models.DateField(blank=True, help_text='Date when seedlings were transplanted to garden', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='days_to_harvest',
            field=models.IntegerField(blank=True, help_text='Days from transplant to harvest', null=True),
        ),
        migrations.AlterField(
            model_name='plantinstance',
            name='planted_date',
            field=models.DateField(blank=True, help_text='Date when this plant was planted (direct sow or transplant)', null=True),
        ),
    ]
