# Generated by Django 4.2.7 on 2025-11-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0009_plant_days_to_germination_plant_direct_sow_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plantinstance',
            name='transplanted_date',
        ),
        migrations.AddField(
            model_name='plant',
            name='days_before_transplant_ready',
            field=models.IntegerField(blank=True, help_text='Days from germination until seedling is ready to transplant (hardening off period)', null=True),
        ),
        migrations.AlterField(
            model_name='plantinstance',
            name='planted_date',
            field=models.DateField(blank=True, help_text='Date when plant was placed in garden plot (either seed_started_date for direct sow, or actual transplant date)', null=True),
        ),
        migrations.AlterField(
            model_name='plantinstance',
            name='seed_started_date',
            field=models.DateField(blank=True, help_text='Date when seeds were started (either indoors in pot or direct sown in garden)', null=True),
        ),
    ]
