# Generated by Django 4.2.7 on 2025-11-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0011_populate_plant_timing_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantinstance',
            name='planned_planting_date',
            field=models.DateField(blank=True, help_text='Planned date to transplant seedlings or direct sow in garden', null=True),
        ),
        migrations.AddField(
            model_name='plantinstance',
            name='planned_seed_start_date',
            field=models.DateField(blank=True, help_text='Planned date to start seeds (in pot or direct sow)', null=True),
        ),
        migrations.AddField(
            model_name='plantinstance',
            name='seed_starting_method',
            field=models.CharField(blank=True, choices=[('pot', 'Started in Pot'), ('direct', 'Direct Sown in Garden')], help_text='How seeds were/will be started', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='plantinstance',
            name='planted_date',
            field=models.DateField(blank=True, help_text='Actual date when plant was placed in garden plot (transplant or direct sow)', null=True),
        ),
        migrations.AlterField(
            model_name='plantinstance',
            name='seed_started_date',
            field=models.DateField(blank=True, help_text='Actual date when seeds were started (in pot or direct sown)', null=True),
        ),
    ]
