# Generated by Django 4.2.7 on 2025-11-18 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0012_add_planned_dates_and_method'),
    ]

    operations = [
        # First, rename the chicago_notes field to growing_notes
        migrations.RenameField(
            model_name='plant',
            old_name='chicago_notes',
            new_name='growing_notes',
        ),
        # Then create the new models
        migrations.CreateModel(
            name='ClimateZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('3a', 'Zone 3a (-40°F to -35°F)'), ('3b', 'Zone 3b (-35°F to -30°F)'), ('4a', 'Zone 4a (-30°F to -25°F)'), ('4b', 'Zone 4b (-25°F to -20°F)'), ('5a', 'Zone 5a (-20°F to -15°F)'), ('5b', 'Zone 5b (-15°F to -10°F)'), ('6a', 'Zone 6a (-10°F to -5°F)'), ('6b', 'Zone 6b (-5°F to 0°F)'), ('7a', 'Zone 7a (0°F to 5°F)'), ('7b', 'Zone 7b (5°F to 10°F)'), ('8a', 'Zone 8a (10°F to 15°F)'), ('8b', 'Zone 8b (15°F to 20°F)'), ('9a', 'Zone 9a (20°F to 25°F)'), ('9b', 'Zone 9b (25°F to 30°F)'), ('10a', 'Zone 10a (30°F to 35°F)'), ('10b', 'Zone 10b (35°F to 40°F)')], help_text='USDA Hardiness Zone', max_length=3, unique=True)),
                ('region_examples', models.CharField(blank=True, help_text='Example cities/regions (e.g., "Chicago, Minneapolis, Portland OR")', max_length=200)),
                ('typical_last_frost', models.CharField(help_text='Typical last spring frost date (MM-DD format)', max_length=5)),
                ('typical_first_frost', models.CharField(help_text='Typical first fall frost date (MM-DD format)', max_length=5)),
                ('avg_annual_min_temp_f', models.IntegerField(help_text='Average annual minimum temperature (Fahrenheit)')),
                ('avg_summer_high_f', models.IntegerField(blank=True, help_text='Average summer high temperature', null=True)),
                ('growing_season_days', models.IntegerField(help_text='Average frost-free days')),
                ('common_soil_types', models.CharField(blank=True, help_text='Common soil types (e.g., "Clay, Loam")', max_length=100)),
                ('humidity_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20)),
                ('special_considerations', models.TextField(blank=True, help_text='Special climate considerations for this zone')),
            ],
            options={
                'verbose_name': 'Climate Zone',
                'verbose_name_plural': 'Climate Zones',
                'ordering': ['zone'],
            },
        ),
        migrations.CreateModel(
            name='PlantZoneData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(choices=[('3a', 'Zone 3a (-40°F to -35°F)'), ('3b', 'Zone 3b (-35°F to -30°F)'), ('4a', 'Zone 4a (-30°F to -25°F)'), ('4b', 'Zone 4b (-25°F to -20°F)'), ('5a', 'Zone 5a (-20°F to -15°F)'), ('5b', 'Zone 5b (-15°F to -10°F)'), ('6a', 'Zone 6a (-10°F to -5°F)'), ('6b', 'Zone 6b (-5°F to 0°F)'), ('7a', 'Zone 7a (0°F to 5°F)'), ('7b', 'Zone 7b (5°F to 10°F)'), ('8a', 'Zone 8a (10°F to 15°F)'), ('8b', 'Zone 8b (15°F to 20°F)'), ('9a', 'Zone 9a (20°F to 25°F)'), ('9b', 'Zone 9b (25°F to 30°F)'), ('10a', 'Zone 10a (30°F to 35°F)'), ('10b', 'Zone 10b (35°F to 40°F)')], max_length=3)),
                ('zone_specific_notes', models.TextField(blank=True, help_text='Growing notes specific to this hardiness zone')),
                ('success_rating', models.IntegerField(choices=[(1, '⭐ Not Recommended'), (2, '⭐⭐ Challenging'), (3, '⭐⭐⭐ Moderate'), (4, '⭐⭐⭐⭐ Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], default=3, help_text='How well this plant grows in this zone')),
                ('soil_amendments', models.TextField(blank=True, help_text='Recommended soil amendments for this zone')),
                ('special_considerations', models.TextField(blank=True, help_text='Special care needed in this zone (e.g., winter protection)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zone_data', to='gardens.plant')),
            ],
            options={
                'verbose_name': 'Plant Zone Data',
                'verbose_name_plural': 'Plant Zone Data',
                'ordering': ['zone', 'plant__name'],
                'indexes': [models.Index(fields=['zone'], name='gardens_pla_zone_008b0a_idx'), models.Index(fields=['plant', 'zone'], name='gardens_pla_plant_i_417559_idx')],
                'unique_together': {('plant', 'zone')},
            },
        ),
    ]
