# Generated by Django 4.2.7 on 2025-11-18 04:39

from django.db import migrations


def migrate_existing_zone_data(apps, schema_editor):
    """
    Migrate existing growing_notes to PlantZoneData for zones 5b and 6a (Chicago zones).
    This preserves the existing Chicago-specific data for backward compatibility.
    """
    Plant = apps.get_model('gardens', 'Plant')
    PlantZoneData = apps.get_model('gardens', 'PlantZoneData')

    # Get all plants that have growing notes
    plants_with_notes = Plant.objects.exclude(growing_notes='').exclude(growing_notes__isnull=True)

    for plant in plants_with_notes:
        # Create zone data for both 5b and 6a (Chicago zones)
        # Assume these are excellent performers since they were in the original Chicago database
        for zone in ['5b', '6a']:
            PlantZoneData.objects.get_or_create(
                plant=plant,
                zone=zone,
                defaults={
                    'zone_specific_notes': plant.growing_notes,
                    'success_rating': 5,  # Excellent - these are proven Chicago plants
                    'soil_amendments': '',  # Can be filled in later
                    'special_considerations': '',  # Can be filled in later
                }
            )


def reverse_migrate_zone_data(apps, schema_editor):
    """Remove all PlantZoneData for zones 5b and 6a"""
    PlantZoneData = apps.get_model('gardens', 'PlantZoneData')
    PlantZoneData.objects.filter(zone__in=['5b', '6a']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0014_populate_climate_zones'),
    ]

    operations = [
        migrations.RunPython(migrate_existing_zone_data, reverse_migrate_zone_data),
    ]
