# Generated by Django 4.2.7 on 2025-11-19 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gardens', '0015_migrate_plant_zone_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='growing_notes',
            field=models.TextField(blank=True, help_text='General growing notes and tips'),
        ),
        migrations.CreateModel(
            name='UserPlantNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for your note', max_length=200)),
                ('note_text', models.TextField(help_text='Your experience growing this plant, tips, observations, etc.')),
                ('growing_season', models.IntegerField(blank=True, help_text='Year you grew this plant (e.g., 2024)', null=True)),
                ('success_rating', models.IntegerField(blank=True, choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='How well did this plant grow for you?', null=True)),
                ('would_grow_again', models.BooleanField(blank=True, help_text='Would you grow this plant again?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notes', to='gardens.plant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'plant'], name='gardens_use_user_id_cfce1b_idx'), models.Index(fields=['plant'], name='gardens_use_plant_i_8d5dde_idx')],
                'unique_together': {('user', 'plant', 'growing_season')},
            },
        ),
    ]
