# Generated by Django 4.2.7 on 2025-11-19 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0016_add_user_plant_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='growing_notes',
        ),
    ]
