# Generated by Django 4.2.7 on 2025-11-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0017_remove_growing_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataMigration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(help_text='Name of the management command (e.g., populate_climate_zones)', max_length=100, unique=True)),
                ('version', models.CharField(help_text='Version of the data (e.g., 1.0.0)', max_length=20)),
                ('last_run', models.DateTimeField(auto_now=True, help_text='Last time this command was executed')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='First time this command was run')),
            ],
            options={
                'verbose_name': 'Data Migration',
                'verbose_name_plural': 'Data Migrations',
                'db_table': 'data_migrations',
                'ordering': ['-last_run'],
            },
        ),
        migrations.AlterField(
            model_name='plantzonedata',
            name='success_rating',
            field=models.IntegerField(choices=[(1, '⭐☆☆☆☆ Not Recommended'), (2, '⭐⭐☆☆☆ Challenging'), (3, '⭐⭐⭐☆☆ Moderate'), (4, '⭐⭐⭐⭐☆ Good'), (5, '⭐⭐⭐⭐⭐ Excellent')], default=3, help_text='How well this plant grows in this zone'),
        ),
    ]
