# Generated by Django 4.2.7 on 2025-11-21 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0018_add_data_migration_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='garden',
            name='garden_type',
            field=models.CharField(choices=[('square_foot', 'Square Foot Gardening'), ('row', 'Row Gardening')], default='square_foot', help_text='Gardening method: Square Foot (intensive) or Row (traditional)', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='row_spacing_between_rows',
            field=models.FloatField(blank=True, help_text='Spacing between rows in row gardening (inches between rows)', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='row_spacing_inches',
            field=models.FloatField(blank=True, help_text='Spacing between plants in row gardening (inches between plants in same row)', null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='sq_ft_spacing',
            field=models.IntegerField(blank=True, help_text='Plants per square foot (e.g., 1, 4, 9, 16). Common: 1=large, 4=medium, 9=small, 16=tiny', null=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='spacing_inches',
            field=models.FloatField(help_text='General spacing between plants in inches (deprecated - use sq_ft_spacing or row_spacing)'),
        ),
    ]
