# Generated by Django 4.2.7 on 2025-11-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gardens', '0019_add_spacing_and_garden_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='pest_susceptibility',
            field=models.TextField(blank=True, help_text='Comma-separated list of pests this plant is susceptible to'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='pest_deterrent_for',
            field=models.TextField(blank=True, help_text='Comma-separated list of pests this plant deters'),
        ),
    ]
