# Generated by Django 5.2.4 on 2025-10-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='years_gardening',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='year_started_gardening',
            field=models.PositiveIntegerField(blank=True, help_text='What year did you start gardening?', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gardening_zone',
            field=models.CharField(blank=True, choices=[('3a', 'Zone 3a (-40°F to -35°F)'), ('3b', 'Zone 3b (-35°F to -30°F)'), ('4a', 'Zone 4a (-30°F to -25°F)'), ('4b', 'Zone 4b (-25°F to -20°F)'), ('5a', 'Zone 5a (-20°F to -15°F)'), ('5b', 'Zone 5b (-15°F to -10°F)'), ('6a', 'Zone 6a (-10°F to -5°F)'), ('6b', 'Zone 6b (-5°F to 0°F)'), ('7a', 'Zone 7a (0°F to 5°F)'), ('7b', 'Zone 7b (5°F to 10°F)'), ('8a', 'Zone 8a (10°F to 15°F)'), ('8b', 'Zone 8b (15°F to 20°F)'), ('9a', 'Zone 9a (20°F to 25°F)'), ('9b', 'Zone 9b (25°F to 30°F)'), ('10a', 'Zone 10a (30°F to 35°F)'), ('10b', 'Zone 10b (35°F to 40°F)')], default='5b', help_text='USDA Hardiness Zone (Chicago is typically 5b/6a)', max_length=10),
        ),
    ]
