# Generated by Django 4.2.7 on 2025-10-22 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_years_gardening_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='anthropic_api_key',
            field=models.CharField(blank=True, help_text='Your Anthropic API key for AI Garden Assistant features (starts with sk-ant-)', max_length=255),
        ),
    ]
