# Generated by Django 4.2.7 on 2025-10-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_anthropic_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='anthropic_api_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='_anthropic_api_key_encrypted',
            field=models.TextField(blank=True, db_column='anthropic_api_key', help_text='Encrypted Anthropic API key for AI Garden Assistant features'),
        ),
    ]
