# Generated by Django 4.2.7 on 2025-11-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_multi_zone_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='notification_timezone',
            field=models.CharField(default='America/Chicago', help_text='Your local timezone for scheduling notifications (e.g., America/New_York, America/Los_Angeles)', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, help_text='Receive daily email notifications about planting and harvest reminders'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weekly_tips',
            field=models.BooleanField(default=True, help_text='Receive weekly gardening digest and tips'),
        ),
    ]
